import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译字典
const translations: Record<Language, Record<string, string>> = {
  zh: {
    // App
    'app.university': '复旦',
    
    // User Panel
    'invite.title': '限时邀请奖励',
    'invite.description': '邀请好友注册即可获得50000积分！',
    'invite.action': '立即邀请',
    'invite.modalTitle': '限时邀请奖励',
    'invite.modalSubtitle': '分享你的邀请链接给好友，注册成功后双方都可获得 50000 积分',
    'invite.shareLink': '分享你的邀请链接',
    'invite.personalCode': '个人邀请码',
    'invite.shareYourCode': '分享你的邀请码',
    'invite.copyLink': '复制链接',
    'invite.copy': '复制',
    'invite.copied': '已复制',
    'invite.value.title': '50000 积分可以做什么？',
    'invite.value.labelValue': '价值',
    'invite.value.labelUsage': '使用量',
    'invite.value.labelAgent': 'Agent',
    'invite.value.equivalent': '约等于 $5',
    'invite.value.deepSearch': '约 700 次 Deep Search、QA 或 Survey',
    'invite.value.agent': '或至少 1 次完整学术Agent 任务',
    'invite.enterCode': '输入邀请码',
    'invite.enterCodePlaceholder': '请输入邀请码',
    'invite.redeem': '兑换',
    'invite.history': '邀请记录',
    'invite.codeRequired': '请输入邀请码',
    'invite.redeemedSuccess': '邀请码兑换成功！',
    'invite.referrals': '邀请人数',
    'subscription.free': 'Free 会员',
    'subscription.upgrade': '升级',
    'credits': 'Credits',
    'recharge': '充值',
    
    // User Menu
    'user.languageSettings': '语言设置',
    'user.downloadClient': '下载客户端',
    'user.download': '下载客户端',
    'user.download.windows': 'Windows 版',
    'user.download.macApple': 'mac（Apple 芯片）',
    'user.download.macIntel': 'mac（Intel 芯片）',
    'user.settings': '我的账户',
    'user.logout': '退出登录',
    'user.membership': '会员信息',
    'user.invite': '邀请好友',
    'user.feedback': '反馈工单',
    
    // Notifications
    'notifications.title': '消息与通知',
    'notifications.learnMore': '了解更多',
    'notifications.feature1.title': 'Scholar QA 表格模式上线',
    'notifications.feature1.description': '全新的表格对比模式让您可以同时查看和比较多篇文献的关键信息，提升文献综述效率。输入"2"即可触发表格生成。',
    'notifications.feature2.title': 'PDF翻译质量优化',
    'notifications.feature2.description': '我们升级了AI翻译引擎，学术论文翻译准确度提升30%，专业术语识别更加精准。',
    'notifications.notice1.title': '新用户福利活动',
    'notifications.notice1.description': '邀请好友注册即可获得100积分奖励，被邀请用户也将获得50积分。活动时间：即日起至3月31日。',
    'notifications.system1.title': '系统更新通知',
    'notifications.system1.description': '平台将于本周末进行系统维护升级，预计耗时2小时。期间可能会影响部分功能使用。',
    'notifications.system2.title': '数据库维护完成',
    'notifications.system2.description': '复旦大学馆藏数据库维护已完成，现已恢复正常访问。感谢您的耐心等待。',
    
    // Left Sidebar
    'nav.library': '我的文库',
    'nav.myPapers': '我的论文',
    'nav.favorites': '我的收藏',
    'nav.readingHistory': '阅读历史',
    'nav.feeds': 'Feeds',
    'nav.scholarQA': '学术问答',
    'nav.home': '主页',
    'nav.newChat': '新对话',
    'nav.scholarSearch': '老搜索',
    'nav.myLibrary': '知识库',
    'nav.reader': '阅读器',
    'nav.allFeeds': '学术搜索',
    'nav.paperReproduction': 'PaperClaw',
    'nav.agents': 'Agents',
    'nav.projects': '研究项目',
    'nav.newScholarQA': '新问答',
    'nav.newLibraryCollection': 'New Scholar Search',
    'nav.recent': '最近',
    'nav.clear': '清除',
    'nav.more': '更多',
    'nav.history': '历史记录',
    'nav.ideaDiscovery': 'Idea Discovery',
    'nav.fudanCollectionSearch': '复旦馆藏搜索',
    'nav.llms': 'LLM分数',
    'nav.tools': '工具',
    'feeds.workspaceTitle': '论文复现工作区',
    'feeds.workspaceDescription': '右侧工作区已建立，可直接在此基础上继续补充布局与交互设计。',
    'feeds.workspaceBadge': '画布已就绪',
    'feeds.emptyCanvasTitle': '等待填充设计内容',
    'feeds.emptyCanvasDescription': '这里保留为 AI Feeds / 论文复现 tab 的主工作区，占位结构和页面边界已经建立，后续可以直接放入模块、卡片或编排组件。',
    'aiFeeds.title': 'AI Feeds',
    'aiFeeds.description': '发现与你当前研究相关的趋势方向与论文。',
    'aiFeeds.refresh': '刷新',
    'aiFeeds.manageInterests': '管理兴趣',
    'aiFeeds.tab.forYou': 'AI 订阅',
    'aiFeeds.tab.latest': '最新',
    'aiFeeds.tab.trends': '趋势',
    'aiFeeds.todayBrief': '今日简报',
    'aiFeeds.searchHero.title': '你好。今天想读哪篇论文？',
    'aiFeeds.searchHero.scholarQaTitle': 'Hi, 开始向你的知识库提问吧。',
    'aiFeeds.firstTimeBrief': '先关注几个主题，逐步个性化你的信息流。',
    'aiFeeds.firstTimeBriefWithSubject': '你已进入 {subject} 信息流。先浏览内容，再逐步补充兴趣与来源。',
    'aiFeeds.broadFeedDescription': '你的信息流当前仍然较宽泛。补充几个兴趣点后，趋势和论文会更聚焦。',
    'aiFeeds.broadFeedDescriptionWithSubject': '当前先按 {subject} 的宽口径内容为你铺开。补充兴趣后，推荐会立刻收敛。',
    'aiFeeds.briefSummaryWithTags': '今天的信息流正向 {tags} 倾斜，趋势与论文推荐会继续根据这些信号实时调整。',
    'aiFeeds.trendsHighlights.title': '趋势亮点',
    'aiFeeds.trendsHighlights.description': '围绕你当前研究重点筛选出的三个趋势方向。',
    'aiFeeds.trendExplorer.title': '趋势浏览',
    'aiFeeds.trendExplorer.description': '查看完整趋势列表，并进一步打开详情了解代表论文与推荐原因。',
    'aiFeeds.latestPapers.title': '最新论文',
    'aiFeeds.latestPapers.description': '按最新信号排序，便于快速浏览近期新增内容。',
    'aiFeeds.recommendedPapers.title': '推荐论文',
    'aiFeeds.recommendedPapers.description': '与上方趋势信号相关的轻量阅读候选。',
    'aiFeeds.recommendedPapers.loading': '正在为你加载论文推荐。',
    'aiFeeds.recommendedPapers.empty': '当前暂无推荐论文。',
    'aiFeeds.recommendedPapers.emptyDescriptionFiltered': '暂时没有论文符合你当前的筛选条件。试着启用更多订阅源或者明天再来看看。',
    'aiFeeds.recommendedPapers.error': '推荐论文加载失败',
    'aiFeeds.recommendedPapers.errorDescription': '生成论文推荐时出现问题。',
    'aiFeeds.whyItMatches': 'Why it matches',
    'aiFeeds.viewBlog': '查看博客',
    'aiFeeds.bookmark': 'Add to Library',
    'aiFeeds.resources': 'Resources',
    'aiFeeds.filters.subject': 'Subject',
    'aiFeeds.filters.interests': '兴趣',
    'aiFeeds.filters.sources': '订阅源',
    'aiFeeds.filters.none': 'None',
    'aiFeeds.resetFilters': '管理筛选',
    'aiFeeds.trends.loadingError': '趋势推荐暂时无法加载',
    'aiFeeds.trends.loadingErrorDescription': '趋势信息流当前不可用，请重试以恢复 mock 数据。',
    'aiFeeds.trends.emptyTitle': '暂无上升趋势',
    'aiFeeds.trends.emptyDescription': '可以尝试放宽兴趣范围，或稍后再来查看。',
    'aiFeeds.trends.allDismissed': '当前可见趋势已全部隐藏。',
    'aiFeeds.retry': '重试',
    'aiFeeds.undo': '撤销',
    'aiFeeds.follow': '关注',
    'aiFeeds.following': '已关注',
    'aiFeeds.followTrend': '关注趋势',
    'aiFeeds.notInterested': '不感兴趣',
    'aiFeeds.viewTrend': '查看趋势',
    'aiFeeds.quickView': '快速查看',
    'aiFeeds.like': '点赞',
    'aiFeeds.saveForLater': '稍后保存',
    'aiFeeds.savedForLater': '已保存稍后读',
    'aiFeeds.compare': '对比',
    'aiFeeds.addToTracker': '加入追踪',
    'aiFeeds.openPaper': '打开论文',
    'aiFeeds.viewFullPaper': '查看全文',
    'aiFeeds.addToReadingQueue': '加入待读',
    'aiFeeds.addedToQueue': '已加入待读',
    'aiFeeds.preferenceUpdated': '你的信息流偏好已更新',
    'aiFeeds.tuneYourFeed': '调整你的信息流',
    'aiFeeds.tuneYourFeedDescription': '用轻量控制项微调推荐结果。',
    'aiFeeds.subject': 'Subject',
    'aiFeeds.subjectNotSet': '尚未设置',
    'aiFeeds.currentFocus': '当前关注',
    'aiFeeds.preferences': '偏好设置',
    'aiFeeds.sources': '来源偏好',
    'aiFeeds.sourcesArxiv': 'arXiv 优先',
    'aiFeeds.sourcesJournals': 'Journals 优先',
    'aiFeeds.sourcesBalanced': '平衡模式',
    'aiFeeds.recentFeedback': '近期反馈',
    'aiFeeds.resetPreferences': '重置偏好',
    'aiFeeds.pickTopics': '先选择几个主题来塑造 AI Feeds。',
    'aiFeeds.noInterestTags': '当前没有启用的兴趣标签。',
    'aiFeeds.followed': '已关注',
    'aiFeeds.dismissed': '已隐藏',
    'aiFeeds.saved': '已保存',
    'aiFeeds.serviceStart.eyebrow': '未开启',
    'aiFeeds.serviceStart.title': '准备好后再启动 AI Feeds',
    'aiFeeds.serviceStart.description': 'AI Feeds 是一项后台持续运行的服务，会持续为你更新论文推荐。运行期间会消耗 credits，你可以随时暂停。',
    'aiFeeds.serviceStart.disclaimer': '进入这个页面不会自动启动 AI Feeds，也不会开始消耗 credits。',
    'aiFeeds.serviceStart.point.background': '开启后会在后台持续运行并更新推荐。',
    'aiFeeds.serviceStart.point.credits': '后台运行期间会持续消耗 credits。',
    'aiFeeds.serviceStart.point.leavePage': '即使离开当前页面，也会继续更新。',
    'aiFeeds.serviceStart.point.pauseAnytime': '你可以随时暂停，暂停后将停止继续消耗。',
    'aiFeeds.serviceStart.point.lowCredits': 'credits 不足时会自动暂停。',
    'aiFeeds.serviceStart.setupTitle': '当前 Feed 配置',
    'aiFeeds.serviceStart.setupDescription': '服务启动后将按下面这组配置持续更新。',
    'aiFeeds.serviceStart.start': 'Start AI Feeds',
    'aiFeeds.serviceStart.notNow': 'Not now',
    'aiFeeds.serviceStart.editSetup': 'Edit setup',
    'aiFeeds.serviceStart.notConfigured': '尚未设置',
    'aiFeeds.serviceConfirm.eyebrow': '启动确认',
    'aiFeeds.serviceConfirm.title': '即将启动后台服务',
    'aiFeeds.serviceConfirm.description': 'AI Feeds 启动后会在后台持续更新推荐。运行期间会持续消耗 credits，但你可以随时暂停。',
    'aiFeeds.serviceConfirm.point.background': '启动后会在后台持续运行并更新。',
    'aiFeeds.serviceConfirm.point.credits': '运行期间会持续消耗 credits。',
    'aiFeeds.serviceConfirm.point.leavePage': '即使离开当前页面，也会继续运行。',
    'aiFeeds.serviceConfirm.point.pauseAnytime': '你可以随时暂停。',
    'aiFeeds.serviceConfirm.point.lowCredits': 'credits 不足时会自动暂停。',
    'aiFeeds.serviceConfirm.confirm': 'Confirm and Start',
    'aiFeeds.serviceConfirm.cancel': 'Cancel',
    'aiFeeds.notice.serviceStayedOff': 'AI Feeds 仍未开启。你可以稍后随时回来启动。',
    'aiFeeds.notice.serviceStarted': 'AI Feeds 已启动，后台更新已开始。',
    'aiFeeds.notice.servicePaused': 'AI Feeds 已暂停，后台更新已停止，也不会继续消耗 credits。',
    'aiFeeds.notice.serviceResumed': 'AI Feeds 已恢复运行，后台更新重新开始。',
    'aiFeeds.notice.servicePausedLowCredits': 'AI Feeds 已因 credits 不足自动暂停。当前不会继续消耗 credits。',
    'aiFeeds.notice.creditsManaged': 'Credits 已更新。你现在可以在余额充足时恢复 AI Feeds。',
    'aiFeeds.notStarted.status': 'Not Started',
    'aiFeeds.notStarted.reason': 'Service is off',
    'aiFeeds.notStarted.title': 'AI Feeds is not running yet',
    'aiFeeds.notStarted.description': '进入页面不会自动启动后台服务。确认启动后，AI Feeds 才会开始后台更新并消耗 credits。',
    'aiFeeds.notStarted.lastUpdated': '最近结果',
    'aiFeeds.notStarted.creditsUsed': '今日已消耗',
    'aiFeeds.notStarted.nextAction': '下一步',
    'aiFeeds.notStarted.start': 'Start AI Feeds',
    'aiFeeds.notStarted.editSetup': 'Edit setup',
    'aiFeeds.lowCreditsWarning.title': 'AI Feeds may pause soon if credits run out',
    'aiFeeds.lowCreditsWarning.description': '当前 credits 已较低。你仍可继续浏览，但如果 credits 耗尽，AI Feeds 将自动暂停。',
    'aiFeeds.lowCreditsWarning.manageCredits': 'Manage credits',
    'aiFeeds.lowCreditsWarning.pauseNow': 'Pause now',
    'aiFeeds.running.status': 'Running',
    'aiFeeds.running.activity': 'Active',
    'aiFeeds.running.title': 'AI Feeds is actively updating in the background',
    'aiFeeds.running.description': '服务正在后台持续更新。你可以继续浏览当前内容，也可以随时暂停。',
    'aiFeeds.running.lastUpdated': '最近更新时间',
    'aiFeeds.running.creditsUsed': '今日已消耗',
    'aiFeeds.running.availableCredits': '可用 Credits',
    'aiFeeds.running.pause': 'Pause',
    'aiFeeds.paused.status': 'Paused',
    'aiFeeds.paused.reason': 'Paused by you',
    'aiFeeds.paused.title': 'AI Feeds is paused',
    'aiFeeds.paused.description': '当前不会获取新的论文更新，也不会继续消耗 credits。你仍然可以继续浏览已经生成的结果。',
    'aiFeeds.paused.lastUpdated': '最后一次更新',
    'aiFeeds.paused.creditsUsed': '今日已消耗',
    'aiFeeds.paused.nextAction': '下一步',
    'aiFeeds.paused.resume': 'Resume',
    'aiFeeds.paused.resultsHint': 'These results are not updating while AI Feeds is paused.',
    'aiFeeds.pauseConfirm.title': '暂停 AI Feeds？',
    'aiFeeds.pauseConfirm.description': '暂停后，当前已生成的推荐内容仍可继续浏览，但不会再获取新的论文更新，也不会继续消耗 credits。',
    'aiFeeds.pauseConfirm.point.keepBrowsing': '当前结果仍然保留，可以继续浏览。',
    'aiFeeds.pauseConfirm.point.noUpdates': '暂停后不会再获取新的论文更新。',
    'aiFeeds.pauseConfirm.point.noCredits': '暂停期间不会继续消耗 credits。',
    'aiFeeds.pauseConfirm.pauseNow': 'Pause now',
    'aiFeeds.pauseConfirm.keepRunning': 'Keep running',
    'aiFeeds.systemPaused.status': 'Paused',
    'aiFeeds.systemPaused.reason': 'Insufficient credits',
    'aiFeeds.systemPaused.title': 'AI Feeds has been automatically paused',
    'aiFeeds.systemPaused.description': '系统已因 credits 不足停止后台更新。当前不会继续消耗 credits，你可以补充 credits 后再恢复。',
    'aiFeeds.systemPaused.lastUpdated': '最后一次更新',
    'aiFeeds.systemPaused.creditsUsed': '今日已消耗',
    'aiFeeds.systemPaused.nextAction': '下一步',
    'aiFeeds.systemPaused.manageCredits': 'Manage credits',
    'aiFeeds.systemPaused.resumeWhenAvailable': 'Resume when available',
    'aiFeeds.systemPaused.resultsHint': 'Results are not being updated because the service is paused.',
    'aiFeeds.preferNewerPapers': '优先更新论文',
    'aiFeeds.preferBreakthroughs': '优先突破性方向',
    'aiFeeds.preferBenchmarks': '优先基准评测',
    'aiFeeds.reduceRepeatedTopics': '减少重复主题',
    'aiFeeds.removedFromList': '已从当前趋势列表中移除。',
    'aiFeeds.detail.noDetail': '暂无趋势详情',
    'aiFeeds.detail.noDetailDescription': '这个趋势暂时没有更多信息。你可以换一个趋势，或刷新后重试。',
    'aiFeeds.detail.loadError': '趋势详情加载失败',
    'aiFeeds.detail.loadErrorDescription': '准备趋势概览时出现问题。',
    'aiFeeds.detail.overview': '概览',
    'aiFeeds.detail.signals': '趋势信号',
    'aiFeeds.detail.paperGrowth': '论文增长',
    'aiFeeds.detail.authorSignal': '作者与实验室信号',
    'aiFeeds.detail.heat': '热度',
    'aiFeeds.detail.heatDescription': '用轻量视图展示不同时间窗口内的近期活跃度。',
    'aiFeeds.detail.representativePapers': '代表论文',
    'aiFeeds.detail.foundational': '奠基工作',
    'aiFeeds.detail.latest': '最新进展',
    'aiFeeds.detail.highlyRelevant': '高度相关',
    'aiFeeds.trendStage.emerging': '新兴',
    'aiFeeds.trendStage.rising': '上升',
    'aiFeeds.trendStage.breakout': '爆发',
    'aiFeeds.trendStage.stable': '稳定',
    'aiFeeds.trendStage.cooling': '降温',
    'aiFeeds.paperRole.foundational': '奠基工作',
    'aiFeeds.paperRole.incremental': '增量进展',
    'aiFeeds.paperRole.evaluation': '评测研究',
    'aiFeeds.paperRole.application': '应用研究',
    'aiFeeds.preview.unavailable': '当前无法加载论文预览。请关闭后从趋势详情中重新尝试。',
    'aiFeeds.preview.empty': '这篇论文的预览详情暂不可用。后续可直接接入真实 API 返回的摘要与元数据。',
    'aiFeeds.preview.whyInTrend': '为什么它会出现在这个趋势中',
    'aiFeeds.preview.aiSummary': 'AI 摘要',
    'aiFeeds.preview.keyTakeaways': '关键要点',
    'aiFeeds.preview.pdfPreview': 'PDF 预览',
    'aiFeeds.preview.openAccessPdf': '开放获取 PDF',
    'aiFeeds.preview.recommendation.deepRead': '值得深入阅读',
    'aiFeeds.preview.recommendation.skimming': '值得快速浏览',
    'aiFeeds.preview.recommendation.later': '适合稍后查看',
    'aiFeeds.preview.noOpenAccessPdf': '没有 Open Access PDF',
    'aiFeeds.preview.noOpenAccessDescription': '暂无 OA，可见占位仅用于说明该论文没有开放获取 PDF。',
    'aiFeeds.preview.noOpenAccessBadge': '无 OA',
    'aiFeeds.preview.noOpenAccessButton': '无 OA PDF',
    'aiFeeds.preview.zoom': '预览放大',
    'aiFeeds.onboarding.title': '首次设置',
    'aiFeeds.onboarding.description': '用简短的分步引导，让 AI Feeds 快速理解你的研究方向并生成第一版工作台。',
    'aiFeeds.onboarding.subjectEyebrow': '首次进入',
    'aiFeeds.onboarding.subjectTitle': '先选择一个 Subject',
    'aiFeeds.onboarding.subjectDescription': '只做这一步即可进入 AI Feeds。兴趣和来源会在主页面内继续渐进补充，不会打断使用。',
    'aiFeeds.onboarding.subjectPlaceholder': '选择一个学科方向',
    'aiFeeds.onboarding.subjectEnterHint': '进入主页后，你可以继续补充 Interests 和 Sources，推荐结果会即时变化。',
    'aiFeeds.onboarding.subjectLoadingTitle': '正在准备 AI Feeds',
    'aiFeeds.onboarding.subjectLoadingDescription': '我们在载入基础信息流结构，很快就能进入主页。',
    'aiFeeds.onboarding.stepLabel': '步骤 {n}',
    'aiFeeds.onboarding.skip': '跳过',
    'aiFeeds.onboarding.skipToFeed': '直接进入 AI Feeds',
    'aiFeeds.onboarding.back': '返回上一步',
    'aiFeeds.onboarding.continue': '继续',
    'aiFeeds.onboarding.enter': '进入 AI Feeds',
    'aiFeeds.onboarding.tryExamples': '试试这些示例',
    'aiFeeds.guidedSetup.eyebrow': '渐进设置',
    'aiFeeds.guidedSetup.title': '在使用中继续微调你的 Feed',
    'aiFeeds.guidedSetup.description': '先看推荐，再补充两个轻量设定。每一步都会立即影响下方的趋势和论文列表。',
    'aiFeeds.guidedSetup.progress': '已完成 {count}/2',
    'aiFeeds.guidedSetup.interestsTitle': '补充 Interests',
    'aiFeeds.guidedSetup.interestsDescription': '添加几个研究兴趣，让推荐更聚焦。',
    'aiFeeds.guidedSetup.interestsDescriptionWithSubject': '基于 {subject} 先补充几个研究兴趣，让推荐更聚焦。',
    'aiFeeds.guidedSetup.interestsEmpty': '还没有额外兴趣。先从几个高频方向开始即可。',
    'aiFeeds.guidedSetup.interestsInputPlaceholder': '补充一个兴趣，例如 Scientific Agents',
    'aiFeeds.guidedSetup.addInterest': '添加兴趣',
    'aiFeeds.guidedSetup.sourcesTitle': '选择 Sources',
    'aiFeeds.guidedSetup.sourcesDescription': '告诉我们你现在更想先看哪些来源，系统会即时重排论文列表。',
    'aiFeeds.guidedSetup.source.arxivTitle': 'arXiv',
    'aiFeeds.guidedSetup.source.arxivDescription': '优先最新预印本和快速上升方向。',
    'aiFeeds.guidedSetup.source.journalsTitle': 'Journals',
    'aiFeeds.guidedSetup.source.journalsDescription': '优先更稳定的正式发表成果。',
    'aiFeeds.guidedSetup.source.balancedTitle': 'Balanced',
    'aiFeeds.guidedSetup.source.balancedDescription': '先保持宽口径，不额外偏向任何来源。',
    'aiFeeds.notice.subjectSelected': '已进入 {subject} 信息流。现在可以直接开始浏览。',
    'aiFeeds.notice.interestAdded': '已添加 {interest}，推荐结果已即时收敛。',
    'aiFeeds.notice.interestRemoved': '已移除 {interest}，信息流已重新平衡。',
    'aiFeeds.notice.sourceArxiv': '现在优先 arXiv，最新预印本会被提前展示。',
    'aiFeeds.notice.sourceJournals': '现在优先 Journals，正式发表成果会被提前展示。',
    'aiFeeds.notice.sourceBalanced': '已恢复平衡来源，推荐会同时覆盖 arXiv 与 Journals。',
    'aiFeeds.notice.sourcesUpdated': '来源筛选已更新，推荐结果已重新整理。',
    'aiFeeds.notice.personalizationApplied': '个性化设置已更新，确认 credits 消耗后已生效。',
    'aiFeeds.notice.reset': '已恢复默认个性化设置。',
    'aiFeeds.manageSetup.title': '管理兴趣与订阅源',
    'aiFeeds.manageSetup.description': '在同一个弹窗内补充研究兴趣，并选择具体订阅来源。',
    'aiFeeds.manageSetup.subjectDescription': '选择当前 feed 的主要 Subject，推荐结果会立即按新的学科方向重排。',
    'aiFeeds.manageSetup.interestsTitle': '兴趣',
    'aiFeeds.manageSetup.interestsDescription': '添加或移除兴趣标签，用于微调推荐相关性。',
    'aiFeeds.manageSetup.interestsEmpty': '当前还没有额外 interests。',
    'aiFeeds.manageSetup.interestsSearch': '搜索或补充兴趣',
    'aiFeeds.manageSetup.sourcesTitle': '订阅源',
    'aiFeeds.manageSetup.sourcesDescription': '搜索具体来源，查看封面卡片，并进行多选过滤。',
    'aiFeeds.manageSetup.sourcesSearch': '搜索来源，例如 arXiv 或 Nature',
    'aiFeeds.manageSetup.push': '推送',
    'aiFeeds.manageSetup.pushHint': '开启推送会持续消耗credits，数量根据你的订阅浮动。',
    'aiFeeds.manageSetup.estimatedCredits': '预计 {count} Credits',
    'aiFeeds.manageSetup.personalizeTitle': '个性化设置',
    'aiFeeds.manageSetup.subscriptionTitle': 'AI 订阅',
    'aiFeeds.manageSetup.subscriptionHint': 'credits消耗量基于您的订阅源和兴趣上下浮动。每篇论文消耗约 1 credit',
    'aiFeeds.manageSetup.interestsInputPlaceholder': '手动输入兴趣方向',
    'aiFeeds.manageSetup.addInterest': '添加',
    'aiFeeds.manageSetup.emailPushTitle': '邮箱推送',
    'aiFeeds.manageSetup.emailPushHint': '开启后通过邮箱接收推荐更新。',
    'aiFeeds.manageSetup.emailLabel': '邮箱',
    'aiFeeds.manageSetup.codeLabel': '验证码',
    'aiFeeds.manageSetup.emailVerified': '已验证',
    'aiFeeds.manageSetup.emailChanged': '邮箱已修改，请重新获取验证码。',
    'aiFeeds.manageSetup.emailRequired': '请输入邮箱地址',
    'aiFeeds.manageSetup.emailInvalid': '请输入有效邮箱地址',
    'aiFeeds.manageSetup.sendCode': '发送验证码',
    'aiFeeds.manageSetup.resendCode': '重新发送',
    'aiFeeds.manageSetup.editEmail': '修改邮箱',
    'aiFeeds.manageSetup.resendIn': '{count}s 后重发',
    'aiFeeds.manageSetup.codeSent': '验证码已发送到 {email}。原型验证码：{code}',
    'aiFeeds.manageSetup.codeSendFirst': '请先发送验证码',
    'aiFeeds.manageSetup.codeLength': '请输入 6 位验证码',
    'aiFeeds.manageSetup.codeInvalid': '验证码错误，请重新输入',
    'aiFeeds.manageSetup.emailVerifiedHint': '邮箱验证成功，保存后生效。',
    'aiFeeds.manageSetup.verifyAndSaveEmail': '验证并保存邮箱',
    'aiFeeds.manageSetup.groupTodayWithCredits': '今日更新了{count}篇文章，消耗{credits}credits',
    'aiFeeds.manageSetup.groupToday': '今日更新了{count}篇文章',
    'aiFeeds.manageSetup.groupUpdatedCount': '{count} 篇文章更新',
    'aiFeeds.manageSetup.sourceSelected': '已选',
    'aiFeeds.sourceType.preprint': '预印本',
    'aiFeeds.sourceType.journalVenue': '期刊 / 会议',
    'aiFeeds.sourceCategory.chemistry': '化学',
    'aiFeeds.sourceCategory.earth-sciences': '地球科学',
    'aiFeeds.sourceCategory.engineering': '工程科学',
    'aiFeeds.sourceCategory.information-science': '信息科学',
    'aiFeeds.sourceCategory.life-sciences': '生命科学',
    'aiFeeds.sourceCategory.materials-science': '材料科学',
    'aiFeeds.sourceCategory.mathematics': '数学',
    'aiFeeds.sourceCategory.medical-sciences': '医学',
    'aiFeeds.sourceCategory.physics': '物理学',
    'aiFeeds.sourceCategory.psychology': '心理学',
    'aiFeeds.manageSetup.cancel': '取消',
    'aiFeeds.manageSetup.apply': '应用修改',
    'aiFeeds.manageSetup.startService': 'Start AI Feeds',
    'aiFeeds.manageSetup.resumeService': 'Resume AI Feeds',
    'aiFeeds.manageSetup.pauseService': 'Pause AI Feeds',
    'aiFeeds.onboarding.previewReady': '你的首个信息流预览已准备好',
    'aiFeeds.onboarding.addTopic': '添加主题',
    'aiFeeds.onboarding.removeTopic': '移除 {topic}',
    'aiFeeds.onboarding.emptyTitle': '暂时没有可展示的预览',
    'aiFeeds.onboarding.emptyDescription': '可以回到上一步补充更明确的研究兴趣，或稍后再试。',
    'aiFeeds.onboarding.errorTitle': '首次设置暂时不可用',
    'aiFeeds.onboarding.errorDescription': '准备 onboarding 数据时出现问题。你可以重试，或稍后再进入 AI Feeds。',
    'aiFeeds.onboarding.step1.title': '30 秒建立你的 AI Feed',
    'aiFeeds.onboarding.step1.short': '研究兴趣',
    'aiFeeds.onboarding.step1.description': '告诉我们你正在做什么，我们会为你找到相关趋势和论文。',
    'aiFeeds.onboarding.step1.placeholder1': '我对多模态推理和 benchmark evaluation 感兴趣。',
    'aiFeeds.onboarding.step1.placeholder2': '跟踪材料 inverse design 的最新工作。',
    'aiFeeds.onboarding.step1.placeholder3': 'RAG, 长上下文, reranking, agents',
    'aiFeeds.onboarding.step1.helperEmpty': '直接描述你的研究主题、论文问题，或贴一段标题与摘要也可以。',
    'aiFeeds.onboarding.step1.helperFilled': '很好。下一步我们会把这些输入解析成你的研究画像，并生成第一版 feed 预览。',
    'aiFeeds.onboarding.step1.readyState': '准备继续',
    'aiFeeds.onboarding.step1.waitingState': '等待输入',
    'aiFeeds.onboarding.step1.skipCta': '跳过并浏览热门 Feed',
    'aiFeeds.onboarding.step2.title': '选择期刊来源',
    'aiFeeds.onboarding.step2.short': '期刊选择',
    'aiFeeds.onboarding.step2.description': '先告诉我们你希望优先关注哪类来源。后续仍然可以调整。',
    'aiFeeds.onboarding.step2.helper': '这是一个轻量偏好，只会影响我们优先展示哪些论文来源。',
    'aiFeeds.onboarding.step2.option.arxiv.title': 'arXiv 优先',
    'aiFeeds.onboarding.step2.option.arxiv.description': '更偏向最新预印本和快速上升方向。',
    'aiFeeds.onboarding.step2.option.journals.title': '期刊与会议',
    'aiFeeds.onboarding.step2.option.journals.description': '更偏向整理后的正式发表成果。',
    'aiFeeds.onboarding.step2.option.balanced.title': '平衡模式',
    'aiFeeds.onboarding.step2.option.balanced.description': '同时保留预印本与正式来源的信号。',
    'aiFeeds.onboarding.step3.title': '检查你的研究画像',
    'aiFeeds.onboarding.step3.short': '研究画像',
    'aiFeeds.onboarding.step3.description': '系统会先把你的输入整理成结构化兴趣标签。删除不相关项，或补充遗漏主题即可。',
    'aiFeeds.onboarding.step3.enterFeed': '进入我的 Feed',
    'aiFeeds.onboarding.step2.empty': '还没有识别到结构化主题。你可以手动添加，或返回上一步重新描述。',
    'aiFeeds.onboarding.step2.addPlaceholder': '补充一个主题，例如 Scientific Agents',
    'aiFeeds.onboarding.step2.loadingTitle': '正在构建你的 feed 画像',
    'aiFeeds.onboarding.step2.loadingDescription': 'AI 正在从你的输入中提取 topics、tasks、methods 和关键词信号。',
    'aiFeeds.onboarding.step2.loadingDescriptionSecondary': '正在理解你的研究兴趣，并为你的 feed 组织第一版画像。',
    'aiFeeds.onboarding.step2.errorTitle': '暂时无法解析你的研究画像',
    'aiFeeds.onboarding.step2.errorDescription': '你可以返回修改输入，或用更明确的研究问题、标题、关键词再试一次。',
    'aiFeeds.onboarding.step2.emptyStateTitle': '还没有足够的结构化信号',
    'aiFeeds.onboarding.step2.emptyStateDescription': '可以快速补充几个主题，系统会据此继续建立你的 AI Feed。',
    'aiFeeds.onboarding.step2.selectedSummary': '当前已选中 {count} 个信号',
    'aiFeeds.onboarding.step2.selectedHint': '高置信度结果已默认选中。点击 chip 可取消或重新选中。',
    'aiFeeds.onboarding.step2.aiAssisted': 'AI 已完成初步整理',
    'aiFeeds.onboarding.step2.group.topics': 'Topics',
    'aiFeeds.onboarding.step2.group.topicsDescription': '研究领域与关注方向',
    'aiFeeds.onboarding.step2.groupEmpty': '当前分组还没有解析结果。',
    'aiFeeds.onboarding.step2.addChipTitle': '补充一个信号',
    'aiFeeds.onboarding.step2.browseTaxonomy': '浏览完整 taxonomy',
    'aiFeeds.onboarding.step2.browseTaxonomyDescription': '作为高级编辑入口，默认保持收起。',
    'aiFeeds.onboarding.step2.buildPreview': '生成预览',
    'aiFeeds.onboarding.step4.title': '预览你的信息流',
    'aiFeeds.onboarding.step4.short': '预览 Feed',
    'aiFeeds.onboarding.step4.description': '基于你的兴趣，我们找到了上升中的趋势和相关论文。',
    'aiFeeds.onboarding.step4.trendsDescription': '以下是 AI Feeds 准备优先推送给你的趋势方向预览。',
    'aiFeeds.onboarding.step4.feedback': '很好，你的 feed 已经开始成形。',
    'aiFeeds.onboarding.step4.refineHint': '进入前你仍然可以返回继续调整。',
    'aiFeeds.onboarding.step4.loadingBadge': '研究助手正在工作',
    'aiFeeds.onboarding.step4.loadingTitle': '正在为你的 feed 生成预览',
    'aiFeeds.onboarding.step4.loadingDescription': '我们正在理解你的研究兴趣，并构建趋势与论文预览。',
    'aiFeeds.onboarding.step4.trendsTitle': '推荐趋势',
    'aiFeeds.onboarding.step4.papersTitle': '推荐论文',
    'aiFeeds.onboarding.step4.papersDescription': '这些论文与上方趋势和你的兴趣信号相关。',
    'aiFeeds.onboarding.step4.whyRelevant': '为什么与你相关',
    'aiFeeds.onboarding.step4.hide': '隐藏',
    'aiFeeds.onboarding.step4.emptyTitle': '还需要再补充一点研究方向',
    'aiFeeds.onboarding.step4.emptyDescription': '当前兴趣信号还比较宽泛。返回上一步补充更具体的主题后，我们就能给出更好的预览。',
    'aiFeeds.onboarding.step4.errorTitle': '暂时无法完成预览',
    'aiFeeds.onboarding.step4.errorDescription': '你可以直接重试，或返回上一步再调整几个兴趣信号。',
    'aiFeeds.onboarding.undoRemovedInterest': '已从研究画像中移除。',
    'aiFeeds.onboarding.undoHiddenPaper': '已从当前预览中隐藏。',
    'aiFeeds.onboarding.complete.title': '你的 AI Feed 已就绪',
    'aiFeeds.onboarding.complete.description': '后续我们会继续根据你的兴趣跟踪趋势和论文。',
    'aiFeeds.onboarding.complete.interests': '已添加兴趣',
    'aiFeeds.onboarding.complete.trends': '个趋势可浏览',
    'aiFeeds.onboarding.complete.papers': '篇论文已推荐',
    'aiFeeds.onboarding.complete.enterFeed': '进入我的 Feed',
    'aiFeeds.onboarding.complete.editInterests': '编辑兴趣',
    'aiFeeds.onboarding.examples.multimodalReasoning': 'Multimodal reasoning',
    'aiFeeds.onboarding.examples.llmAgents': 'LLM agents',
    'aiFeeds.onboarding.examples.ragEvaluation': 'RAG evaluation',
    'aiFeeds.onboarding.examples.robotics': 'Robotics',
    'aiFeeds.onboarding.examples.medicalImaging': 'Medical imaging',
    'aiFeeds.onboarding.examples.inverseDesign': 'Inverse design',
    
    // Search Modes
    'search.quickMode': '快速模式',
    'search.deepMode': '深度模式',
    'search.books': '图书馆及特藏推荐',
    'search.theses': '本校学位论文',
    'search.title': '深度搜索',
    'search.description': '基于用户意图验证。适合进行具有特定标准（如特定任务或数据集）的文献综述研究。',
    
    // Search Tabs
    'search.tab.papers': '学术论文',
    'search.tab.fudanLibrary': '复旦大学馆藏资源',
    'search.tab.fudanResearch': '复旦大学学术成果',
    
    // Categories
    'category.libraryCollections': '图书馆及特藏推荐',
    'category.undergraduateTheses': '本校学位论文',
    'category.computerScience': '计算机科学',
    'category.medicine': '医学',
    'category.biology': '生物学',
    'category.chemistry': '化学',
    'category.finance': '金融学',
    'category.environmentalScience': '环境科学',
    'category.math': '数学',
    'category.engineering': '工程学',
    'category.physics': '物理学',
    'category.psychology': '心理学',
    'category.literature': '文学',
    'category.design': '设计学',
    'category.journalism': '新闻学',
    'category.cs': '计算机科学',
    'category.socialScience': '社会科学',
    'category.naturalScience': '自然科学',
    
    // Example Queries - Library Collections
    'example.library.1': '帮我找找中国古代建筑史的图书',
    'example.library.2': '帮我找一些入门级的学习数据可视化图书',
    'example.library.3': '你能推荐给我类似傲慢与偏见的书吗',
    
    // Example Queries - Undergraduate Theses
    'example.undergrad.1': '复旦历年硕博论文中关于人工智能伦理的研究有哪些',
    'example.undergrad.2': '查找本校近5年机器学习相关的博士论文',
    'example.undergrad.3': '复旦新闻学院关于媒体融合的学位论文',
    
    // Example Queries - Computer Science
    'example.cs.1': '寻找使用蒸馏方法训练模型的论文',
    'example.cs.2': '寻找最近3年研究AI4Science的论文',
    'example.cs.3': '寻找关于LLM模因理解的论文',
    
    // Example Queries - Medicine
    'example.medicine.1': '寻找关于癌症免疫疗法的研究',
    'example.medicine.2': '寻找关于COVID-19疫苗有效性的论文',
    'example.medicine.3': '寻找关于个性化医疗方法的研究',
    
    // Example Queries - Biology
    'example.biology.1': '寻找关于CRISPR基因编辑应用的论文',
    'example.biology.2': '寻找关于微生物组与人类健康的研究',
    'example.biology.3': '寻找关于进化生物学机制的研究',
    
    // Example Queries - Chemistry
    'example.chemistry.1': '寻找关于绿色化学和可持续合成的论文',
    'example.chemistry.2': '寻找关于有机化学催化的研究',
    'example.chemistry.3': '寻找关于纳米材料性质的研究',
    
    // Example Queries - Finance
    'example.finance.1': '寻找关于金融预测中机器学习的论文',
    'example.finance.2': '寻找关于加密货币和区块链的研究',
    'example.finance.3': '寻找关于行为金融学理论的研究',
    
    // Example Queries - Environmental Science
    'example.envScience.1': '寻找关于气候变化缓解策略的论文',
    'example.envScience.2': '寻找关于可再生能源技术的研究',
    'example.envScience.3': '寻找关于生物多样性保护的研究',
    
    // Example Queries - Math
    'example.math.1': '寻找关于代数拓扑应用的论文',
    'example.math.2': '寻找关于数论问题的研究',
    'example.math.3': '寻找关于计算数学的研究',
    
    // Example Queries - Engineering
    'example.engineering.1': '寻找关于自动驾驶技术的论文',
    'example.engineering.2': '寻找关于可持续工程设计的研究',
    'example.engineering.3': '寻找关于机器人与自动化的研究',
    
    // Example Queries - Physics
    'example.physics.1': '寻找关于量子计算突破的论文',
    'example.physics.2': '寻找关于暗物质检测的研究',
    'example.physics.3': '寻找关于粒子物理实验的研究',
    
    // Example Queries - Psychology
    'example.psychology.1': '寻找关于认知行为疗法有效性的论文',
    'example.psychology.2': '寻找关于社会心理学与行为的研究',
    'example.psychology.3': '寻找关于神经心理学机制的研究',
    
    // Book Categories Examples
    'example.book.literature.1': '推荐关于现代主义文学的经典著作',
    'example.book.literature.2': '寻找中国当代文学研究的重要文献',
    'example.book.literature.3': '查找莎士比亚作品的中文译本及评论',
    'example.book.design.1': '推荐平面设计基础理论书籍',
    'example.book.design.2': '寻找用户体验设计的实践指南',
    'example.book.design.3': '查找建筑设史关的专业文献',
    'example.book.journalism.1': '推荐新媒体传播学的前沿著作',
    'example.book.journalism.2': '寻找新闻采访与写作技巧的教',
    'example.book.journalism.3': '查找数据新闻可视化的实用指南',
    
    // Theses Categories Examples
    'example.theses.cs.1': '复旦历年硕博论文中关于人工智能伦理的研究有哪些',
    'example.theses.cs.2': '查找本校近5年机器学习相关的博士论文',
    'example.theses.cs.3': '寻找计算机视觉方向的优秀硕士学位论文',
    'example.theses.social.1': '复旦新闻学院关于媒体融合的学位论文',
    'example.theses.social.2': '查找本校经济学院关于数字经济的研究论文',
    'example.theses.social.3': '寻找社会学系关于城市化问题的博士论文',
    'example.theses.natural.1': '复旦生命科学学院关于基因编辑的学位论文',
    'example.theses.natural.2': '查找本校化学系关于新材料研发的研究成果',
    'example.theses.natural.3': '寻找物理学系关于量子计算的博士论文',
    
    // Table Mode
    'table.switch': '切换为表格模式',
    'table.backToNormal': '返回普通模式',
    
    // Resource Types
    'resource.paper': '论文',
    'resource.book': '图书',
    'resource.thesis': '学位论文',
    'resource.special': '特藏资料',
    'resource.dataset': '数据集',
    
    // Common
    'loading': '加载中...',
    'search': '搜索',
    'cancel': '取消',
    'confirm': '确认',
    'save': '保存',
    'delete': '删除',
    'edit': '编辑',
    
    // Paper Reproduction
    'reproduction.title': '论文复现',
    'reproduction.description': '上传研究论文PDF并提供复现说明，AI将为您生成详细的实验计划',
    'reproduction.uploadPDF': '上传论文PDF',
    'reproduction.dragDrop': '拖拽PDF文件到此处，或',
    'reproduction.browse': '浏览文件',
    'reproduction.fileSupport': '支持最大50MB的PDF文件',
    'reproduction.changeFile': '更换文件',
    'reproduction.uploadError': '请上传PDF文件',
    'reproduction.additionalNotes': '补充说明（可选）',
    'reproduction.notesDescription': '请描述您的复现需求、特殊配置或实验重点，支持Markdown格式',
    'reproduction.notesPlaceholder': '例如：\n- 请使用较小的模型规模进行测试\n- 重点关注注意力机制的可视化\n- 需要在单GPU环境下运行\n- 对比不同学习率的影响',
    'reproduction.generatePlan': '生成实验计划',
    
    // Workflow Steps
    'workflow.step1': '上传文件',
    'workflow.step1.desc': '上传PDF并说明需求',
    'workflow.step2': '确认方案',
    'workflow.step2.desc': '审阅AI生成的实验计划',
    'workflow.step3': '执行实验',
    'workflow.step3.desc': '提供数据并启动复现',
    'workflow.step4': '查看报告',
    'workflow.step4.desc': '获取完整的实验结果',
    
    'reproduction.avgTime': '平均完成时间',
    
    // Report Card
    'report.title': '实验报告已生成',
    'report.subtitle': '所有复现任务已成功完成',
    'report.filename': '复现报告',
    'report.generatedAt': '生成于',
    'report.duration': '总耗时',
    'report.downloadPDF': '下载PDF报告',
    'report.viewOnline': '在线查看',
    'report.shareReport': '分享报告',
    
    // Report Metrics
    'report.metrics.title': '核心指标',
    'report.metrics.bleuScore': 'BLEU分数',
    'report.metrics.accuracy': '准确率',
    'report.metrics.loss': '最终损失',
    'report.metrics.trainTime': '训练时长',
    
    // Report Highlights
    'report.highlights.title': '关键发现',
    'report.highlights.item1': '模型在测试集上达到了27.8 BLEU分数，超过论文原始结果',
    'report.highlights.item2': '注意力机制可视化显示良好的词对齐效果',
    'report.highlights.item3': '训练收敛稳定，未出现梯度爆炸或消失问题',
  },
  en: {
    // App
    'app.university': 'Fudan',
    
    // User Panel
    'invite.title': 'Limited-Time Invitation Rewards',
    'invite.description': 'Invite friends to register and get 50000 credits!',
    'invite.action': 'Invite Now',
    'invite.modalTitle': 'Limited-Time Invitation Rewards',
    'invite.modalSubtitle': 'Share your invitation link with friends. Once they sign up successfully, both of you will receive 50000 credits.',
    'invite.shareLink': 'Share your invitation link',
    'invite.personalCode': 'Personal invitation code',
    'invite.shareYourCode': 'Share your invite code',
    'invite.copyLink': 'Copy link',
    'invite.copy': 'Copy',
    'invite.copied': 'Copied!',
    'invite.value.title': 'What can 50000 credits do?',
    'invite.value.labelValue': 'Value',
    'invite.value.labelUsage': 'Usage',
    'invite.value.labelAgent': 'Agent',
    'invite.value.equivalent': 'About $5 in value',
    'invite.value.deepSearch': 'Roughly 700 Deep Search, QA, or Survey runs',
    'invite.value.agent': 'Or at least one full academic Agent task',
    'invite.enterCode': 'Enter invitation code',
    'invite.enterCodePlaceholder': 'Enter invitation code',
    'invite.redeem': 'Redeem',
    'invite.history': 'Invitation History',
    'invite.codeRequired': 'Please enter an invitation code',
    'invite.redeemedSuccess': 'Invitation code redeemed!',
    'invite.referrals': 'Referrals',
    'subscription.free': 'Free Member',
    'subscription.upgrade': 'Upgrade',
    'credits': 'Credits',
    'recharge': 'Recharge',
    
    // User Menu
    'user.languageSettings': 'Language Settings',
    'user.downloadClient': 'Download App',
    'user.download': 'Download App',
    'user.download.windows': 'Windows',
    'user.download.macApple': 'macOS (Apple Silicon)',
    'user.download.macIntel': 'macOS (Intel)',
    'user.settings': 'My Account',
    'user.logout': 'Logout',
    'user.membership': 'Membership Info',
    'user.invite': 'Invite Friends',
    'user.feedback': 'Feedback ticket',
    
    // Notifications
    'notifications.title': 'Messages & Notifications',
    'notifications.learnMore': 'Learn More',
    'notifications.feature1.title': 'Scholar QA Table Mode Launched',
    'notifications.feature1.description': 'The new table comparison mode allows you to view and compare key information from multiple papers simultaneously, enhancing literature review efficiency. Enter "2" to generate the table.',
    'notifications.feature2.title': 'PDF Translation Quality Improvement',
    'notifications.feature2.description': 'We have upgraded the AI translation engine, improving the accuracy of academic paper translations by 30% and enhancing the precision of professional term recognition.',
    'notifications.notice1.title': 'New User Bonus Activity',
    'notifications.notice1.description': 'Invite friends to register and earn 100 credits. Invited users will also receive 50 credits. Activity period: Now to March 31.',
    'notifications.system1.title': 'System Update Notification',
    'notifications.system1.description': 'The platform will undergo system maintenance and upgrade this weekend, expected to take 2 hours. This may affect the use of some features.',
    'notifications.system2.title': 'Database Maintenance Completed',
    'notifications.system2.description': 'The Fudan University library database maintenance is complete and is now back to normal access. Thank you for your patience.',
    
    // Left Sidebar
    'nav.library': 'My Library',
    'nav.myPapers': 'My Papers',
    'nav.favorites': 'Favorites',
    'nav.readingHistory': 'Reading History',
    'nav.feeds': 'Feeds',
    'nav.scholarQA': 'Scholar QA',
    'nav.home': 'Home',
    'nav.newChat': 'New Chat',
    'nav.scholarSearch': 'Old Search',
    'nav.myLibrary': 'My Library',
    'nav.reader': 'Reader',
    'nav.allFeeds': 'Scholar Search',
    'nav.paperReproduction': 'PaperClaw',
    'nav.agents': 'Agents',
    'nav.projects': 'Research Projects',
    'nav.newScholarQA': 'New Scholar QA',
    'nav.newLibraryCollection': 'New Scholar Search',
    'nav.recent': 'Recent',
    'nav.clear': 'Clear',
    'nav.more': 'More',
    'nav.history': 'History',
    'nav.ideaDiscovery': 'Idea Discovery',
    'nav.fudanCollectionSearch': 'Fudan Collection Search',
    'nav.llms': 'LLM Scores',
    'nav.tools': 'Tools',
    'feeds.workspaceTitle': 'AI Feeds Workspace',
    'feeds.workspaceDescription': 'The right-side workspace is now in place and ready for your next design pass.',
    'feeds.workspaceBadge': 'Canvas Ready',
    'feeds.emptyCanvasTitle': 'Waiting for design content',
    'feeds.emptyCanvasDescription': 'This area is reserved as the main workspace for the AI Feeds tab. The page shell and layout boundaries are ready for modules, cards, and future interactions.',
    'aiFeeds.title': 'AI Feeds',
    'aiFeeds.description': 'Discover research directions and papers relevant to your current work.',
    'aiFeeds.refresh': 'Refresh',
    'aiFeeds.manageInterests': 'Manage Interests',
    'aiFeeds.tab.forYou': 'AI Feeds',
    'aiFeeds.tab.latest': 'Latest',
    'aiFeeds.tab.trends': 'Trends',
    'aiFeeds.todayBrief': 'Today Brief',
    'aiFeeds.searchHero.title': 'Hi. Which paper do you want to read today?',
    'aiFeeds.searchHero.scholarQaTitle': 'Ask anything based on your own library.',
    'aiFeeds.firstTimeBrief': 'Start by following a few topics to personalize your feed.',
    'aiFeeds.firstTimeBriefWithSubject': 'You are now in the {subject} feed. Start browsing first, then refine interests and sources in-page.',
    'aiFeeds.broadFeedDescription': 'Your feed is still broad. Add a few interests to make the trends and papers more targeted.',
    'aiFeeds.broadFeedDescriptionWithSubject': 'The feed is currently broad within {subject}. Add interests and the recommendations will tighten immediately.',
    'aiFeeds.briefSummaryWithTags': 'Today’s feed is leaning toward {tags}, and the trend and paper picks are updating around those signals in real time.',
    'aiFeeds.trendsHighlights.title': 'Trends Highlights',
    'aiFeeds.trendsHighlights.description': 'Three trend recommendations selected around your current research focus.',
    'aiFeeds.trendExplorer.title': 'Trend Explorer',
    'aiFeeds.trendExplorer.description': 'Browse the full trend list and open details to inspect representative papers and recommendation rationale.',
    'aiFeeds.latestPapers.title': 'Latest Papers',
    'aiFeeds.latestPapers.description': 'Sorted by recent signals so you can scan newly surfaced papers first.',
    'aiFeeds.recommendedPapers.title': 'Recommended Papers',
    'aiFeeds.recommendedPapers.description': 'Lightweight reading candidates connected to the trend signals above.',
    'aiFeeds.recommendedPapers.loading': 'Loading paper recommendations for your current feed.',
    'aiFeeds.recommendedPapers.empty': 'No recommended papers available right now.',
    'aiFeeds.recommendedPapers.emptyDescriptionFiltered': 'No papers match your current filters right now. Try enabling more sources or check back tomorrow.',
    'aiFeeds.recommendedPapers.error': 'Unable to load recommended papers',
    'aiFeeds.recommendedPapers.errorDescription': 'Something went wrong while preparing paper recommendations.',
    'aiFeeds.whyItMatches': 'Why it matches',
    'aiFeeds.viewBlog': 'View blog',
    'aiFeeds.bookmark': 'Add to Library',
    'aiFeeds.resources': 'Resources',
    'aiFeeds.filters.subject': 'Subject',
    'aiFeeds.filters.interests': 'Interests',
    'aiFeeds.filters.sources': 'Sources',
    'aiFeeds.filters.none': 'None',
    'aiFeeds.resetFilters': 'Manage Filters',
    'aiFeeds.trends.loadingError': 'Unable to load trend recommendations',
    'aiFeeds.trends.loadingErrorDescription': 'The trend feed is temporarily unavailable. Retry to restore the current mock dataset.',
    'aiFeeds.trends.emptyTitle': 'No rising trends yet',
    'aiFeeds.trends.emptyDescription': 'Try broadening your interests or check back later.',
    'aiFeeds.trends.allDismissed': 'All visible trends were dismissed.',
    'aiFeeds.retry': 'Retry',
    'aiFeeds.undo': 'Undo',
    'aiFeeds.follow': 'Follow',
    'aiFeeds.following': 'Following',
    'aiFeeds.followTrend': 'Follow Trend',
    'aiFeeds.notInterested': 'Not Interested',
    'aiFeeds.viewTrend': 'View Trend',
    'aiFeeds.quickView': 'Quick View',
    'aiFeeds.like': 'Like',
    'aiFeeds.saveForLater': 'Save for Later',
    'aiFeeds.savedForLater': 'Saved for Later',
    'aiFeeds.compare': 'Compare',
    'aiFeeds.addToTracker': 'Add to Tracker',
    'aiFeeds.openPaper': 'Open Paper',
    'aiFeeds.viewFullPaper': 'View Full Paper',
    'aiFeeds.addToReadingQueue': 'Add to Reading Queue',
    'aiFeeds.addedToQueue': 'Added to Queue',
    'aiFeeds.preferenceUpdated': 'Your feed preferences have been updated',
    'aiFeeds.tuneYourFeed': 'Tune Your Feed',
    'aiFeeds.tuneYourFeedDescription': 'Lightweight controls for steering recommendations.',
    'aiFeeds.subject': 'Subject',
    'aiFeeds.subjectNotSet': 'Not set',
    'aiFeeds.currentFocus': 'Current Focus',
    'aiFeeds.preferences': 'Preferences',
    'aiFeeds.sources': 'Source Focus',
    'aiFeeds.sourcesArxiv': 'arXiv First',
    'aiFeeds.sourcesJournals': 'Journals First',
    'aiFeeds.sourcesBalanced': 'Balanced',
    'aiFeeds.recentFeedback': 'Recent Feedback',
    'aiFeeds.resetPreferences': 'Reset preferences',
    'aiFeeds.pickTopics': 'Pick a few topics to shape AI Feeds.',
    'aiFeeds.noInterestTags': 'No active interest tags.',
    'aiFeeds.followed': 'Followed',
    'aiFeeds.dismissed': 'Dismissed',
    'aiFeeds.saved': 'Saved',
    'aiFeeds.serviceStart.eyebrow': 'Not Started',
    'aiFeeds.serviceStart.title': 'Start AI Feeds when you are ready',
    'aiFeeds.serviceStart.description': 'AI Feeds is a background service that continuously updates your paper recommendations. While it is running, it uses credits, and you can pause it anytime.',
    'aiFeeds.serviceStart.disclaimer': 'Entering this page does not start AI Feeds or use any credits.',
    'aiFeeds.serviceStart.point.background': 'Runs continuously in the background after you start it.',
    'aiFeeds.serviceStart.point.credits': 'Uses credits while it is running.',
    'aiFeeds.serviceStart.point.leavePage': 'Keeps updating even if you leave this page.',
    'aiFeeds.serviceStart.point.pauseAnytime': 'Can be paused at any time, and no more credits are used while paused.',
    'aiFeeds.serviceStart.point.lowCredits': 'Pauses automatically if your credits run low.',
    'aiFeeds.serviceStart.setupTitle': 'Current feed setup',
    'aiFeeds.serviceStart.setupDescription': 'AI Feeds will run using the configuration below once started.',
    'aiFeeds.serviceStart.start': 'Start AI Feeds',
    'aiFeeds.serviceStart.notNow': 'Not now',
    'aiFeeds.serviceStart.editSetup': 'Edit setup',
    'aiFeeds.serviceStart.notConfigured': 'Not set',
    'aiFeeds.serviceConfirm.eyebrow': 'Start Confirmation',
    'aiFeeds.serviceConfirm.title': 'You are about to start a background service',
    'aiFeeds.serviceConfirm.description': 'Once started, AI Feeds keeps updating your recommendations in the background. It uses credits while running, and you can pause it anytime.',
    'aiFeeds.serviceConfirm.point.background': 'AI Feeds will continue updating in the background.',
    'aiFeeds.serviceConfirm.point.credits': 'Credits are used while it is running.',
    'aiFeeds.serviceConfirm.point.leavePage': 'It keeps running even if you leave this page.',
    'aiFeeds.serviceConfirm.point.pauseAnytime': 'You can pause it at any time.',
    'aiFeeds.serviceConfirm.point.lowCredits': 'It pauses automatically if your credits run low.',
    'aiFeeds.serviceConfirm.confirm': 'Confirm and Start',
    'aiFeeds.serviceConfirm.cancel': 'Cancel',
    'aiFeeds.notice.serviceStayedOff': 'AI Feeds is still off. You can start it anytime.',
    'aiFeeds.notice.serviceStarted': 'AI Feeds is now running in the background.',
    'aiFeeds.notice.servicePaused': 'AI Feeds was paused. Background updates have stopped and no more credits are being used.',
    'aiFeeds.notice.serviceResumed': 'AI Feeds resumed. Background updates are running again.',
    'aiFeeds.notice.servicePausedLowCredits': 'AI Feeds was automatically paused because credits are too low. No more credits are being used now.',
    'aiFeeds.notice.creditsManaged': 'Credits updated. You can resume AI Feeds once enough credits are available.',
    'aiFeeds.notStarted.status': 'Not Started',
    'aiFeeds.notStarted.reason': 'Service is off',
    'aiFeeds.notStarted.title': 'AI Feeds is not running yet',
    'aiFeeds.notStarted.description': 'Entering this page does not start the background service. AI Feeds only begins updating and using credits after you confirm start.',
    'aiFeeds.notStarted.lastUpdated': 'Last results',
    'aiFeeds.notStarted.creditsUsed': 'Used today',
    'aiFeeds.notStarted.nextAction': 'Next action',
    'aiFeeds.notStarted.start': 'Start AI Feeds',
    'aiFeeds.notStarted.editSetup': 'Edit setup',
    'aiFeeds.lowCreditsWarning.title': 'AI Feeds may pause soon if credits run out',
    'aiFeeds.lowCreditsWarning.description': 'Credits are running low. You can keep browsing, but AI Feeds may pause automatically if credits run out.',
    'aiFeeds.lowCreditsWarning.manageCredits': 'Manage credits',
    'aiFeeds.lowCreditsWarning.pauseNow': 'Pause now',
    'aiFeeds.running.status': 'Running',
    'aiFeeds.running.activity': 'Active',
    'aiFeeds.running.title': 'AI Feeds is actively updating in the background',
    'aiFeeds.running.description': 'The service is still running in the background. You can keep browsing the feed or pause it at any time.',
    'aiFeeds.running.lastUpdated': 'Last updated',
    'aiFeeds.running.creditsUsed': 'Used today',
    'aiFeeds.running.availableCredits': 'Available credits',
    'aiFeeds.running.pause': 'Pause',
    'aiFeeds.paused.status': 'Paused',
    'aiFeeds.paused.reason': 'Paused by you',
    'aiFeeds.paused.title': 'AI Feeds is paused',
    'aiFeeds.paused.description': 'No new updates are being fetched while paused, and no more credits are being used. Your current results remain available.',
    'aiFeeds.paused.lastUpdated': 'Last updated',
    'aiFeeds.paused.creditsUsed': 'Used today',
    'aiFeeds.paused.nextAction': 'Next action',
    'aiFeeds.paused.resume': 'Resume',
    'aiFeeds.paused.resultsHint': 'These results are not updating while AI Feeds is paused.',
    'aiFeeds.pauseConfirm.title': 'Pause AI Feeds?',
    'aiFeeds.pauseConfirm.description': 'Your current recommendations will remain available, but AI Feeds will stop fetching new updates and stop using credits while paused.',
    'aiFeeds.pauseConfirm.point.keepBrowsing': 'Your current results stay available for browsing.',
    'aiFeeds.pauseConfirm.point.noUpdates': 'No new paper updates will be fetched while paused.',
    'aiFeeds.pauseConfirm.point.noCredits': 'No additional credits are used while paused.',
    'aiFeeds.pauseConfirm.pauseNow': 'Pause now',
    'aiFeeds.pauseConfirm.keepRunning': 'Keep running',
    'aiFeeds.systemPaused.status': 'Paused',
    'aiFeeds.systemPaused.reason': 'Insufficient credits',
    'aiFeeds.systemPaused.title': 'AI Feeds has been automatically paused',
    'aiFeeds.systemPaused.description': 'Background updates have stopped because your credits are too low. No more credits are being used, and you can resume later once credits are available.',
    'aiFeeds.systemPaused.lastUpdated': 'Last updated',
    'aiFeeds.systemPaused.creditsUsed': 'Used today',
    'aiFeeds.systemPaused.nextAction': 'Next action',
    'aiFeeds.systemPaused.manageCredits': 'Manage credits',
    'aiFeeds.systemPaused.resumeWhenAvailable': 'Resume when available',
    'aiFeeds.systemPaused.resultsHint': 'Results are not being updated because the service is paused.',
    'aiFeeds.preferNewerPapers': 'Prefer newer papers',
    'aiFeeds.preferBreakthroughs': 'Prefer breakthroughs',
    'aiFeeds.preferBenchmarks': 'Prefer benchmarks',
    'aiFeeds.reduceRepeatedTopics': 'Reduce repeated topics',
    'aiFeeds.removedFromList': 'was removed from your current trend list.',
    'aiFeeds.detail.noDetail': 'No trend detail available',
    'aiFeeds.detail.noDetailDescription': 'This trend does not have expanded detail yet. Try another trend or refresh the feed.',
    'aiFeeds.detail.loadError': 'Unable to load trend detail',
    'aiFeeds.detail.loadErrorDescription': 'Something went wrong while preparing this trend overview.',
    'aiFeeds.detail.overview': 'Overview',
    'aiFeeds.detail.signals': 'Trend Signals',
    'aiFeeds.detail.paperGrowth': 'Paper growth',
    'aiFeeds.detail.authorSignal': 'Author and lab signal',
    'aiFeeds.detail.heat': 'Heat',
    'aiFeeds.detail.heatDescription': 'A lightweight view of recent activity over different time windows.',
    'aiFeeds.detail.representativePapers': 'Representative Papers',
    'aiFeeds.detail.foundational': 'Foundational',
    'aiFeeds.detail.latest': 'Latest',
    'aiFeeds.detail.highlyRelevant': 'Highly Relevant',
    'aiFeeds.trendStage.emerging': 'Emerging',
    'aiFeeds.trendStage.rising': 'Rising',
    'aiFeeds.trendStage.breakout': 'Breakout',
    'aiFeeds.trendStage.stable': 'Stable',
    'aiFeeds.trendStage.cooling': 'Cooling',
    'aiFeeds.paperRole.foundational': 'Foundational',
    'aiFeeds.paperRole.incremental': 'Incremental',
    'aiFeeds.paperRole.evaluation': 'Evaluation',
    'aiFeeds.paperRole.application': 'Application',
    'aiFeeds.preview.unavailable': 'Unable to load paper preview right now. Close and retry from the trend detail panel.',
    'aiFeeds.preview.empty': 'Preview details are not available for this paper yet. The shell is ready for future API-backed summaries and metadata.',
    'aiFeeds.preview.whyInTrend': 'Why this paper is in this trend',
    'aiFeeds.preview.aiSummary': 'AI Summary',
    'aiFeeds.preview.keyTakeaways': 'Key Takeaways',
    'aiFeeds.preview.pdfPreview': 'PDF Preview',
    'aiFeeds.preview.openAccessPdf': 'Open Access PDF',
    'aiFeeds.preview.recommendation.deepRead': 'Worth a deep read',
    'aiFeeds.preview.recommendation.skimming': 'Worth skimming',
    'aiFeeds.preview.recommendation.later': 'Save for later',
    'aiFeeds.preview.noOpenAccessPdf': 'No Open Access PDF',
    'aiFeeds.preview.noOpenAccessDescription': 'No OA is available. This placeholder indicates that the paper does not have an open-access PDF.',
    'aiFeeds.preview.noOpenAccessBadge': 'No OA',
    'aiFeeds.preview.noOpenAccessButton': 'No OA PDF',
    'aiFeeds.preview.zoom': 'Preview Zoom',
    'aiFeeds.onboarding.title': 'First-Time Setup',
    'aiFeeds.onboarding.description': 'A short guided flow that helps AI Feeds understand your research context and assemble the first workspace.',
    'aiFeeds.onboarding.subjectEyebrow': 'First Entry',
    'aiFeeds.onboarding.subjectTitle': 'Start with one subject',
    'aiFeeds.onboarding.subjectDescription': 'This is the only step before entering AI Feeds. Interests and sources are refined inside the homepage without interrupting use.',
    'aiFeeds.onboarding.subjectPlaceholder': 'Select a subject',
    'aiFeeds.onboarding.subjectEnterHint': 'After entering, you can refine interests and sources in-page and the feed will update instantly.',
    'aiFeeds.onboarding.subjectLoadingTitle': 'Preparing AI Feeds',
    'aiFeeds.onboarding.subjectLoadingDescription': 'Loading the base feed structure so you can enter the homepage directly.',
    'aiFeeds.onboarding.stepLabel': 'Step {n}',
    'aiFeeds.onboarding.skip': 'Skip',
    'aiFeeds.onboarding.skipToFeed': 'Go to AI Feeds',
    'aiFeeds.onboarding.back': 'Back',
    'aiFeeds.onboarding.continue': 'Continue',
    'aiFeeds.onboarding.enter': 'Enter AI Feeds',
    'aiFeeds.onboarding.tryExamples': 'Try an example',
    'aiFeeds.guidedSetup.eyebrow': 'Guided Setup',
    'aiFeeds.guidedSetup.title': 'Refine the feed while you use it',
    'aiFeeds.guidedSetup.description': 'Browse first, then add two lightweight settings. Each step immediately changes the trend and paper lists below.',
    'aiFeeds.guidedSetup.progress': '{count}/2 complete',
    'aiFeeds.guidedSetup.interestsTitle': 'Add Interests',
    'aiFeeds.guidedSetup.interestsDescription': 'Add a few research interests to narrow the feed.',
    'aiFeeds.guidedSetup.interestsDescriptionWithSubject': 'Start from {subject} and add a few research interests to narrow the feed.',
    'aiFeeds.guidedSetup.interestsEmpty': 'No extra interests yet. Start with a few high-signal directions.',
    'aiFeeds.guidedSetup.interestsInputPlaceholder': 'Add an interest, for example Scientific Agents',
    'aiFeeds.guidedSetup.addInterest': 'Add Interest',
    'aiFeeds.guidedSetup.sourcesTitle': 'Choose Sources',
    'aiFeeds.guidedSetup.sourcesDescription': 'Tell us which sources you want first and we will rerank the paper list immediately.',
    'aiFeeds.guidedSetup.source.arxivTitle': 'arXiv',
    'aiFeeds.guidedSetup.source.arxivDescription': 'Prioritize recent preprints and fast-moving directions.',
    'aiFeeds.guidedSetup.source.journalsTitle': 'Journals',
    'aiFeeds.guidedSetup.source.journalsDescription': 'Prioritize more established published work.',
    'aiFeeds.guidedSetup.source.balancedTitle': 'Balanced',
    'aiFeeds.guidedSetup.source.balancedDescription': 'Keep the feed broad without preferring one source type yet.',
    'aiFeeds.notice.subjectSelected': 'Entered the {subject} feed. You can start browsing immediately.',
    'aiFeeds.notice.interestAdded': '{interest} added. Recommendations were updated immediately.',
    'aiFeeds.notice.interestRemoved': '{interest} removed. The feed was rebalanced.',
    'aiFeeds.notice.sourceArxiv': 'arXiv is now prioritized, so recent preprints move up first.',
    'aiFeeds.notice.sourceJournals': 'Journals are now prioritized, so published work moves up first.',
    'aiFeeds.notice.sourceBalanced': 'Balanced sources restored. The feed now mixes arXiv and journals again.',
    'aiFeeds.notice.sourcesUpdated': 'Source filters updated. Recommendations were refreshed.',
    'aiFeeds.notice.personalizationApplied': 'Personalization updated and applied after confirming credit usage.',
    'aiFeeds.notice.reset': 'Default personalization settings restored.',
    'aiFeeds.manageSetup.title': 'Manage Interests and Sources',
    'aiFeeds.manageSetup.description': 'Use one dialog to refine interests and choose specific sources.',
    'aiFeeds.manageSetup.subjectDescription': 'Choose the primary subject for this feed. Recommendations update immediately when you switch it.',
    'aiFeeds.manageSetup.interestsTitle': 'Interests',
    'aiFeeds.manageSetup.interestsDescription': 'Add or remove interest tags to tune relevance.',
    'aiFeeds.manageSetup.interestsEmpty': 'No extra interests selected yet.',
    'aiFeeds.manageSetup.interestsSearch': 'Search or add interests',
    'aiFeeds.manageSetup.sourcesTitle': 'Sources',
    'aiFeeds.manageSetup.sourcesDescription': 'Search specific sources, review their cover cards, and multi-select them.',
    'aiFeeds.manageSetup.sourcesSearch': 'Search sources like arXiv or Nature',
    'aiFeeds.manageSetup.push': 'Push',
    'aiFeeds.manageSetup.pushHint': 'Enabling push will keep consuming credits, and the amount varies with your subscription.',
    'aiFeeds.manageSetup.estimatedCredits': 'Estimated {count} Credits',
    'aiFeeds.manageSetup.personalizeTitle': 'Personalize Settings',
    'aiFeeds.manageSetup.subscriptionTitle': 'AI Feeds',
    'aiFeeds.manageSetup.subscriptionHint': 'Credit usage varies based on your sources and interests. Each paper costs about 1 credit.',
    'aiFeeds.manageSetup.interestsInputPlaceholder': 'Manually enter an interest',
    'aiFeeds.manageSetup.addInterest': 'Add',
    'aiFeeds.manageSetup.emailPushTitle': 'Email Delivery',
    'aiFeeds.manageSetup.emailPushHint': 'Receive recommendation updates by email when enabled.',
    'aiFeeds.manageSetup.emailLabel': 'Email',
    'aiFeeds.manageSetup.codeLabel': 'Verification Code',
    'aiFeeds.manageSetup.emailVerified': 'Verified',
    'aiFeeds.manageSetup.emailChanged': 'Email changed. Please request a new verification code.',
    'aiFeeds.manageSetup.emailRequired': 'Please enter an email address',
    'aiFeeds.manageSetup.emailInvalid': 'Please enter a valid email address',
    'aiFeeds.manageSetup.sendCode': 'Send Code',
    'aiFeeds.manageSetup.resendCode': 'Resend',
    'aiFeeds.manageSetup.editEmail': 'Edit Email',
    'aiFeeds.manageSetup.resendIn': 'Resend in {count}s',
    'aiFeeds.manageSetup.codeSent': 'Verification code sent to {email}. Prototype code: {code}',
    'aiFeeds.manageSetup.codeSendFirst': 'Send a verification code first',
    'aiFeeds.manageSetup.codeLength': 'Enter the 6-digit verification code',
    'aiFeeds.manageSetup.codeInvalid': 'Incorrect verification code. Try again.',
    'aiFeeds.manageSetup.emailVerifiedHint': 'Email verified. Save to apply.',
    'aiFeeds.manageSetup.verifyAndSaveEmail': 'Verify and Save Email',
    'aiFeeds.manageSetup.groupTodayWithCredits': '{count} papers updated today, using {credits} credits',
    'aiFeeds.manageSetup.groupToday': '{count} papers updated today',
    'aiFeeds.manageSetup.groupUpdatedCount': '{count} papers updated',
    'aiFeeds.manageSetup.sourceSelected': 'Selected',
    'aiFeeds.sourceType.preprint': 'Preprint',
    'aiFeeds.sourceType.journalVenue': 'Journal / Venue',
    'aiFeeds.sourceCategory.chemistry': 'Chemistry',
    'aiFeeds.sourceCategory.earth-sciences': 'Earth Sciences',
    'aiFeeds.sourceCategory.engineering': 'Engineering',
    'aiFeeds.sourceCategory.information-science': 'Information Science',
    'aiFeeds.sourceCategory.life-sciences': 'Life Sciences',
    'aiFeeds.sourceCategory.materials-science': 'Materials Science',
    'aiFeeds.sourceCategory.mathematics': 'Mathematics',
    'aiFeeds.sourceCategory.medical-sciences': 'Medical Sciences',
    'aiFeeds.sourceCategory.physics': 'Physics',
    'aiFeeds.sourceCategory.psychology': 'Psychology',
    'aiFeeds.manageSetup.cancel': 'Cancel',
    'aiFeeds.manageSetup.apply': 'Apply changes',
    'aiFeeds.manageSetup.startService': 'Start AI Feeds',
    'aiFeeds.manageSetup.resumeService': 'Resume AI Feeds',
    'aiFeeds.manageSetup.pauseService': 'Pause AI Feeds',
    'aiFeeds.onboarding.previewReady': 'Your first feed preview is ready',
    'aiFeeds.onboarding.addTopic': 'Add Topic',
    'aiFeeds.onboarding.removeTopic': 'Remove {topic}',
    'aiFeeds.onboarding.emptyTitle': 'No preview is available yet',
    'aiFeeds.onboarding.emptyDescription': 'Go back and add a more specific description of your work, or try again later.',
    'aiFeeds.onboarding.errorTitle': 'Onboarding is temporarily unavailable',
    'aiFeeds.onboarding.errorDescription': 'There was a problem preparing the onboarding preview. Retry now or return to AI Feeds later.',
    'aiFeeds.onboarding.step1.title': 'Build your AI Feed in 30 seconds',
    'aiFeeds.onboarding.step1.short': 'Interests',
    'aiFeeds.onboarding.step1.description': 'Tell us what you’re working on, and we’ll find relevant trends and papers for you.',
    'aiFeeds.onboarding.step1.placeholder1': 'I’m interested in multimodal reasoning and benchmark evaluation.',
    'aiFeeds.onboarding.step1.placeholder2': 'Track new work on inverse design for materials.',
    'aiFeeds.onboarding.step1.placeholder3': 'RAG, long context, reranking, agents',
    'aiFeeds.onboarding.step1.helperEmpty': 'Describe your research in your own words, or paste a paper title, abstract, or problem statement.',
    'aiFeeds.onboarding.step1.helperFilled': 'Good. We’ll use this to infer your research profile and prepare a first-pass feed preview.',
    'aiFeeds.onboarding.step1.readyState': 'Ready to continue',
    'aiFeeds.onboarding.step1.waitingState': 'Waiting for input',
    'aiFeeds.onboarding.step1.skipCta': 'Skip and explore popular feeds',
    'aiFeeds.onboarding.step2.title': 'Choose your preferred sources',
    'aiFeeds.onboarding.step2.short': 'Sources',
    'aiFeeds.onboarding.step2.description': 'Tell us which sources to prioritize first. You can change this later.',
    'aiFeeds.onboarding.step2.helper': 'This is a lightweight preference that only affects which paper sources we prioritize first.',
    'aiFeeds.onboarding.step2.option.arxiv.title': 'arXiv first',
    'aiFeeds.onboarding.step2.option.arxiv.description': 'Lean toward the latest preprints and fast-moving directions.',
    'aiFeeds.onboarding.step2.option.journals.title': 'Journals and venues',
    'aiFeeds.onboarding.step2.option.journals.description': 'Lean toward more established published work.',
    'aiFeeds.onboarding.step2.option.balanced.title': 'Balanced mix',
    'aiFeeds.onboarding.step2.option.balanced.description': 'Keep both preprint and published signals in the mix.',
    'aiFeeds.onboarding.step3.title': 'Review your research profile',
    'aiFeeds.onboarding.step3.short': 'Profile',
    'aiFeeds.onboarding.step3.description': 'We turned your input into a set of topics and signals. Edit anything before we build your feed.',
    'aiFeeds.onboarding.step3.enterFeed': 'Enter My Feed',
    'aiFeeds.onboarding.step2.empty': 'No structured topics yet. Add one manually or go back and revise your description.',
    'aiFeeds.onboarding.step2.addPlaceholder': 'Add a topic, for example Scientific Agents',
    'aiFeeds.onboarding.step2.loadingTitle': 'Building your feed profile',
    'aiFeeds.onboarding.step2.loadingDescription': 'AI is extracting topics, tasks, methods, and keyword signals from your input.',
    'aiFeeds.onboarding.step2.loadingDescriptionSecondary': 'Understanding your research interests and organizing a first-pass profile for your feed.',
    'aiFeeds.onboarding.step2.errorTitle': 'We could not parse your research profile yet',
    'aiFeeds.onboarding.step2.errorDescription': 'Go back and revise the input, or try a clearer research question, title, or set of keywords.',
    'aiFeeds.onboarding.step2.emptyStateTitle': 'Not enough structured signals yet',
    'aiFeeds.onboarding.step2.emptyStateDescription': 'Add a few suggested topics and we can keep building your AI Feed from there.',
    'aiFeeds.onboarding.step2.selectedSummary': '{count} signals selected',
    'aiFeeds.onboarding.step2.selectedHint': 'High-confidence results are selected by default. Click a chip to deselect or reselect it.',
    'aiFeeds.onboarding.step2.aiAssisted': 'AI-organized first pass',
    'aiFeeds.onboarding.step2.group.topics': 'Topics',
    'aiFeeds.onboarding.step2.group.topicsDescription': 'Research areas and focus directions',
    'aiFeeds.onboarding.step2.groupEmpty': 'No signals in this group yet.',
    'aiFeeds.onboarding.step2.addChipTitle': 'Add a signal',
    'aiFeeds.onboarding.step2.browseTaxonomy': 'Browse full taxonomy',
    'aiFeeds.onboarding.step2.browseTaxonomyDescription': 'An advanced editing entry point that stays collapsed by default.',
    'aiFeeds.onboarding.step2.buildPreview': 'Build Preview',
    'aiFeeds.onboarding.step4.title': 'Here’s a preview of your feed',
    'aiFeeds.onboarding.step4.short': 'Preview',
    'aiFeeds.onboarding.step4.description': 'Based on your interests, we found rising trends and relevant papers.',
    'aiFeeds.onboarding.step4.trendsDescription': 'A preview of the trend directions AI Feeds would prioritize for you.',
    'aiFeeds.onboarding.step4.feedback': 'Great start — your feed is already taking shape.',
    'aiFeeds.onboarding.step4.refineHint': 'You can still go back and refine it before entering.',
    'aiFeeds.onboarding.step4.loadingBadge': 'Research assistant at work',
    'aiFeeds.onboarding.step4.loadingTitle': 'Building a preview for your feed...',
    'aiFeeds.onboarding.step4.loadingDescription': 'Understanding your research interests and preparing trends and papers for you.',
    'aiFeeds.onboarding.step4.trendsTitle': 'Recommended Trends',
    'aiFeeds.onboarding.step4.papersTitle': 'Recommended Papers',
    'aiFeeds.onboarding.step4.papersDescription': 'These papers line up with the trend directions and research signals in your profile.',
    'aiFeeds.onboarding.step4.whyRelevant': 'Why this is relevant to you',
    'aiFeeds.onboarding.step4.hide': 'Hide',
    'aiFeeds.onboarding.step4.emptyTitle': 'We need a bit more direction',
    'aiFeeds.onboarding.step4.emptyDescription': 'Your current signals are still quite broad. Go back and add a more specific topic and we’ll prepare a better preview.',
    'aiFeeds.onboarding.step4.errorTitle': 'We couldn’t build the preview just yet',
    'aiFeeds.onboarding.step4.errorDescription': 'Retry now, or go back and adjust a few interest signals before we try again.',
    'aiFeeds.onboarding.undoRemovedInterest': 'was removed from your research profile.',
    'aiFeeds.onboarding.undoHiddenPaper': 'was hidden from this preview.',
    'aiFeeds.onboarding.complete.title': 'Your AI Feed is ready',
    'aiFeeds.onboarding.complete.description': 'We’ll keep tracking trends and papers based on your interests.',
    'aiFeeds.onboarding.complete.interests': 'interests added',
    'aiFeeds.onboarding.complete.trends': 'trends ready to explore',
    'aiFeeds.onboarding.complete.papers': 'papers recommended',
    'aiFeeds.onboarding.complete.enterFeed': 'Enter My Feed',
    'aiFeeds.onboarding.complete.editInterests': 'Edit interests',
    'aiFeeds.onboarding.examples.multimodalReasoning': 'Multimodal reasoning',
    'aiFeeds.onboarding.examples.llmAgents': 'LLM agents',
    'aiFeeds.onboarding.examples.ragEvaluation': 'RAG evaluation',
    'aiFeeds.onboarding.examples.robotics': 'Robotics',
    'aiFeeds.onboarding.examples.medicalImaging': 'Medical imaging',
    'aiFeeds.onboarding.examples.inverseDesign': 'Inverse design',
    
    // Search Modes
    'search.quickMode': 'Quick Mode',
    'search.deepMode': 'Deep Mode',
    'search.books': 'Library & Special Collections',
    'search.theses': 'University Theses',
    'search.title': 'Deep Search',
    'search.description': 'Based on user intent verification. Ideal for researchers conducting literature reviews with specific criteria, such as a specific task or dataset.',
    
    // Search Tabs
    'search.tab.papers': 'Academic Papers',
    'search.tab.fudanLibrary': 'Fudan University Library Resources',
    'search.tab.fudanResearch': 'Fudan University Research Achievements',
    
    // Categories
    'category.libraryCollections': 'Library & Special Collections',
    'category.undergraduateTheses': 'University Theses',
    'category.computerScience': 'Computer Science',
    'category.medicine': 'Medicine',
    'category.biology': 'Biology',
    'category.chemistry': 'Chemistry',
    'category.finance': 'Finance',
    'category.environmentalScience': 'Environmental Science',
    'category.math': 'Math',
    'category.engineering': 'Engineering',
    'category.physics': 'Physics',
    'category.psychology': 'Psychology',
    'category.literature': 'Literature',
    'category.design': 'Design',
    'category.journalism': 'Journalism',
    'category.cs': 'Computer Science',
    'category.socialScience': 'Social Science',
    'category.naturalScience': 'Natural Science',
    
    // Example Queries - Library Collections
    'example.library.1': 'Help me find books on ancient Chinese architecture history',
    'example.library.2': 'Find me some beginner-level books on data visualization',
    'example.library.3': 'Can you recommend books similar to Pride and Prejudice?',
    
    // Example Queries - Undergraduate Theses
    'example.undergrad.1': 'What research on AI ethics exists in Fudan\'s graduate theses?',
    'example.undergrad.2': 'Find doctoral theses related to machine learning from the past 5 years',
    'example.undergrad.3': 'Fudan School of Journalism theses on media convergence',
    
    // Example Queries - Computer Science
    'example.cs.1': 'Find papers using distillation methods to train models',
    'example.cs.2': 'Find me papers that study AI4Science in recent 3 years',
    'example.cs.3': 'Find papers on LLM meme understanding',
    
    // Example Queries - Medicine
    'example.medicine.1': 'Find research on immunotherapy for cancer treatment',
    'example.medicine.2': 'Find papers about COVID-19 vaccine effectiveness',
    'example.medicine.3': 'Find studies on personalized medicine approaches',
    
    // Example Queries - Biology
    'example.biology.1': 'Find papers on CRISPR gene editing applications',
    'example.biology.2': 'Find research about microbiome and human health',
    'example.biology.3': 'Find studies on evolutionary biology mechanisms',
    
    // Example Queries - Chemistry
    'example.chemistry.1': 'Find papers on green chemistry and sustainable synthesis',
    'example.chemistry.2': 'Find research about catalysis in organic chemistry',
    'example.chemistry.3': 'Find studies on nanomaterials properties',
    
    // Example Queries - Finance
    'example.finance.1': 'Find papers on machine learning in financial forecasting',
    'example.finance.2': 'Find research about cryptocurrency and blockchain',
    'example.finance.3': 'Find studies on behavioral finance theories',
    
    // Example Queries - Environmental Science
    'example.envScience.1': 'Find papers on climate change mitigation strategies',
    'example.envScience.2': 'Find research about renewable energy technologies',
    'example.envScience.3': 'Find studies on biodiversity conservation',
    
    // Example Queries - Math
    'example.math.1': 'Find papers on algebraic topology applications',
    'example.math.2': 'Find research about number theory problems',
    'example.math.3': 'Find studies on computational mathematics',
    
    // Example Queries - Engineering
    'example.engineering.1': 'Find papers on autonomous vehicle technology',
    'example.engineering.2': 'Find research about sustainable engineering design',
    'example.engineering.3': 'Find studies on robotics and automation',
    
    // Example Queries - Physics
    'example.physics.1': 'Find papers on quantum computing breakthroughs',
    'example.physics.2': 'Find research about dark matter detection',
    'example.physics.3': 'Find studies on particle physics experiments',
    
    // Example Queries - Psychology
    'example.psychology.1': 'Find papers on cognitive behavioral therapy effectiveness',
    'example.psychology.2': 'Find research about social psychology and behavior',
    'example.psychology.3': 'Find studies on neuropsychology mechanisms',
    
    // Book Categories Examples
    'example.book.literature.1': 'Recommend classic works on modernist literature',
    'example.book.literature.2': 'Find important literature on contemporary Chinese literature',
    'example.book.literature.3': 'Find Chinese translations and reviews of Shakespeare\'s works',
    'example.book.design.1': 'Recommend books on graphic design fundamentals',
    'example.book.design.2': 'Find practical guides on user experience design',
    'example.book.design.3': 'Find professional literature on architectural design history',
    'example.book.journalism.1': 'Recommend cutting-edge works on new media communication',
    'example.book.journalism.2': 'Find textbooks on news interviewing and writing techniques',
    'example.book.journalism.3': 'Find practical guides on data journalism visualization',
    
    // Theses Categories Examples
    'example.theses.cs.1': 'What research on AI ethics exists in Fudan\'s graduate theses?',
    'example.theses.cs.2': 'Find doctoral theses related to machine learning from the past 5 years',
    'example.theses.cs.3': 'Find excellent master\'s theses in computer vision',
    'example.theses.social.1': 'Fudan School of Journalism theses on media convergence',
    'example.theses.social.2': 'Find research papers on digital economy from the Economics school',
    'example.theses.social.3': 'Find doctoral theses on urbanization from the Sociology department',
    'example.theses.natural.1': 'Fudan School of Life Sciences theses on gene editing',
    'example.theses.natural.2': 'Find research on new materials from the Chemistry department',
    'example.theses.natural.3': 'Find doctoral theses on quantum computing from the Physics department',
    
    // Table Mode
    'table.switch': 'Switch to Table Mode',
    'table.backToNormal': 'Back to Normal Mode',
    
    // Resource Types
    'resource.paper': 'Paper',
    'resource.book': 'Book',
    'resource.thesis': 'Thesis',
    'resource.special': 'Special Collection',
    'resource.dataset': 'Dataset',
    
    // Common
    'loading': 'Loading...',
    'search': 'Search',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    
    // Paper Reproduction
    'reproduction.title': 'Paper Reproduction',
    'reproduction.description': 'Upload research paper PDF and provide reproduction instructions, AI will generate a detailed experimental plan for you',
    'reproduction.uploadPDF': 'Upload Paper PDF',
    'reproduction.dragDrop': 'Drag and drop PDF file here, or',
    'reproduction.browse': 'Browse Files',
    'reproduction.fileSupport': 'Supports PDF files up to 50MB',
    'reproduction.changeFile': 'Change File',
    'reproduction.uploadError': 'Please upload a PDF file',
    'reproduction.additionalNotes': 'Additional Notes (Optional)',
    'reproduction.notesDescription': 'Describe your reproduction requirements, special configurations, or experimental focus, supports Markdown format',
    'reproduction.notesPlaceholder': 'Example:\n- Please use a smaller model size for testing\n- Focus on the visualization of attention mechanisms\n- Need to run in a single GPU environment\n- Compare the effects of different learning rates',
    'reproduction.generatePlan': 'Generate Experimental Plan',
    
    // Workflow Steps
    'workflow.step1': 'Upload File',
    'workflow.step1.desc': 'Upload PDF and specify requirements',
    'workflow.step2': 'Confirm Plan',
    'workflow.step2.desc': 'Review the experimental plan generated by AI',
    'workflow.step3': 'Execute Experiment',
    'workflow.step3.desc': 'Provide data and start reproduction',
    'workflow.step4': 'View Report',
    'workflow.step4.desc': 'Obtain the complete experimental results',
    
    'reproduction.avgTime': 'Average Completion Time',
    
    // Report Card
    'report.title': 'Experimental Report Generated',
    'report.subtitle': 'All reproduction tasks have been successfully completed',
    'report.filename': 'Reproduction Report',
    'report.generatedAt': 'Generated at',
    'report.duration': 'Total Duration',
    'report.downloadPDF': 'Download PDF Report',
    'report.viewOnline': 'View Online',
    'report.shareReport': 'Share Report',
    
    // Report Metrics
    'report.metrics.title': 'Key Metrics',
    'report.metrics.bleuScore': 'BLEU Score',
    'report.metrics.accuracy': 'Accuracy',
    'report.metrics.loss': 'Final Loss',
    'report.metrics.trainTime': 'Training Time',
    
    // Report Highlights
    'report.highlights.title': 'Key Findings',
    'report.highlights.item1': 'The model achieved a BLEU score of 27.8 on the test set, exceeding the original result in the paper',
    'report.highlights.item2': 'Attention mechanism visualization shows good word alignment effects',
    'report.highlights.item3': 'Training convergence is stable, with no gradient explosion or vanishing issues',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string, params?: Record<string, string>): string => {
    const template = translations[language][key] || key;
    if (!params) {
      return template;
    }

    return Object.entries(params).reduce(
      (result, [paramKey, value]) => result.replaceAll(`{${paramKey}}`, value),
      template,
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // Fallback for hot reload scenarios where provider reference is lost
    const fallbackT = (key: string, params?: Record<string, string>): string => {
      const template = translations['zh'][key] || key;
      if (!params) {
        return template;
      }

      return Object.entries(params).reduce(
        (result, [paramKey, value]) => result.replaceAll(`{${paramKey}}`, value),
        template,
      );
    };
    return { language: 'zh' as Language, setLanguage: (() => {}) as (lang: Language) => void, t: fallbackT };
  }
  return context;
}
